# Utilise une image Nginx Alpine pour réduire la taille
FROM nginx:alpine

# Supprime la configuration par défaut
RUN rm /etc/nginx/conf.d/default.conf

# Copie ta configuration Nginx
COPY nginx.conf /etc/nginx/conf.d/

# Copie les fichiers du client
COPY client/ /usr/share/nginx/html/

# Expose le port 80
EXPOSE 80

# La commande par défaut de Nginx est déjà correcte
CMD ["nginx", "-g", "daemon off;"]