version: '3.8'

services:
  server:
    build:
      context: ./server
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 3
    environment:
      - PORT=8080

  client:
    build:
      context: .
      dockerfile: client/Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
